### ISSUE TITLE
If file is in a saved state, tests are not generated in Visual Studio Code with the save-shortcut

### ISSUE THREAD

**Issue by JukicDejan** [symflower/symflower#11]
Hi,

this occurs with the Visual Studio Extension.

I have the file Copy.java

```
public class Copy {
    static String[] copy(String[] from, String[] to) {
        for (int i = 0; i < from.length; i++) {
            to[i] = from[i];
        }

        return to;
    }
}
```

The state of the file is already saved, so no changes. When I hit Ctrl+S the tests are not generated, probably because the saving event is not triggered.

**Comment by zimmski** [comment]
@JukicDejan since this works for me on two different machines and in our CI: let's find the difference in setup on your machine

a. Since you reported in another issue that the binary did not work with your Glibc version and that is now fixed. Can you go into the extension view and make sure that your version is at least v22711 and that it does not say "reload required" (or something simliar)

b. Are you sure that it didn't just took longer than usual to generate a file?

c. Here is a video on how i do the save and then open the output of the extension. Can you post the output here (or upload it as a Gist)

![saving-and-vsce-output](https://user-images.githubusercontent.com/1847950/168760937-6a759e50-0252-4a45-a324-266e8325cb66.gif)

d. Can you please try the [console version](https://symflower.com/en/products/symflower-cli/tutorial/cli-java/) to make sure that this is a Visual Studio Code problem. Change with a console into the workspace and then do a `symflower $filePath`. Does that generate tests? If not, please post the output.

**Comment by JukicDejan** [comment]
Hi,

I have reinstalled the extension and Test generation works when the file has changes and is saved. Console version works.

**Comment by zimmski** [comment]
Since the save-event is send when there are changes, this seems like a difference in the usual configuration maybe? 

Can you try over the command menu (usually CTRL+SHIFT+P), type in "File: Save"

- e. does this entry show the shortcut "CTRL + S" on the right side?
- f. does this command work when you hit enter or click on it with your mouse?

**Comment by JukicDejan** [comment]
e: It does not show CTRL + S on the side
f: this command works, it generates tests even when it is in a saved state.

**Comment by zimmski** [comment]
Does it show anything on the side of that command like in the video above? Because if there is nothing there, i think that means that there is no shortcut set for that command. Hence, pressing CTRL+S does not do anything.

Do you maybe have "Auto Save" activated?

**Comment by JukicDejan** [comment]
There is no shortcut displayed in the "File: Save" entry.

Generating tests with CTRL+S works however when there are changes.

Auto Save is not activated.

**Comment by zimmski** [comment]
@JukicDejan would you be up for a live session with me to resolve this issue? Cannot reproduce this locally.

**Comment by JukicDejan** [comment]
Sure, send me a Google Meets invite, today at 18:30 would work.

**Comment by zimmski** [comment]
Currently doing a session with @JukicDejan. Interestingly there was a second keybinding with CTR+S with "Save all" that did not send a save-event over the language server. Removing that second keybinding fixed the problem. The additional binding came from an extension unrelated to Symflower.

**Comment by JukicDejan** [comment]
Resolved, a save all files extension was colliding with the key binding.
