### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by springapidev** [symflower/symflower#17]
- Issue Type: `Performance`
- Extension Name: `symflower`
- Extension Version: `0.0.25839`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.72.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/DELL/AppData/Local/Temp/Symflower.symflower-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bauersimon** [comment]
@springapidev thank you for reporting this. It seems there is no actual `<...>.cpuprofile.txt` file attached in your report. Is there any chance you have the file available still? We would need it to inspect what exactly caused this problem on your side.

**Comment by zimmski** [comment]
@springapidev we did fix a considerable amount of performance problems since version 25839 of Symflower. Could you please try again and make the Symflower log available. You can find the log by opening the command menu with CTRL+SHIFT+P then type in "View: Focus on Output View" and then there select "Symflower" in the combo box. That should help us to pinpoint where your problem could be coming from.

One open problem we have is that our Go implementation for dependencies and our Java implementation for Maven are CPU intensive and slow, so maybe that is the problem. If you are up to a video call we could look at this together which makes fixing it much faster.

Until we have more information, i will close this issue since there is nothing to work on for us.
