### ISSUE TITLE
IntelliJ Idea internal error: executable "java" cannot be found in $PATH which is needed for parsing Java files

### ISSUE THREAD

**Issue by novoj** [symflower/symflower#21]
The Symflower is unusable in current version of IntelliJ Idea. Attempt to use it results in following log in Symflower tab.

```
Checking for updates
Latest version already installed
Initializing language server
symflower v26054 on linux/amd64

KernelVersion: 5.15.0-48-generic
PATH: /home/jno/.local/share/JetBrains/IntelliJIdea2022.2/Symflower/share/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ProductName: Ubuntu
ProductVersion: 20.04
Handling request(1, "initialize")
Acceptable workspace: evita (/www/evita/)
Responding to request(1, "initialize")
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x1a, 0x46, 0x69, 0x15, 0x5a, 0xcc, 0x11, 0xed, 0x94, 0xf5, 0x54, 0x5, 0xdb, 0x52, 0x3a, 0x56}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating unit tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /www/evita/
Search for Java files
internal error: executable "java" cannot be found in $PATH which is needed for parsing Java files
Sending request(symflower/refresh-files)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x1a, 0x46, 0x69, 0x15, 0x5a, 0xcc, 0x11, 0xed, 0x94, 0xf5, 0x54, 0x5, 0xdb, 0x52, 0x3a, 0x56}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
```

It seems that it takes PATH from `/etc/environment` and doesn't respect extension in user profile. It could also get the path from the IntelliJ but probably fails to do this either:

![image](https://user-images.githubusercontent.com/202912/199549507-e8e13379-04f2-4cb7-8006-f1f2e4232c46.png)

**Comment by zimmski** [comment]
@novoj @camdenorrb this problem is fixed with version 26559. It is not yet a full fix since there are variations of these settings that need some more work, but we are now supporting the JDK project settings of JetBrain's editors.

Please give it a try and let me know how it goes. We are especially interested in feedback for the smart test templates, e.g. https://twitter.com/symflower/status/1595771724993372165.

**Comment by novoj** [comment]
I can confirm, it generates something now - but in bad folder and in this quality:

![image](https://user-images.githubusercontent.com/202912/205583772-4f41890b-c044-4415-9315-de7e718d56d1.png)

But this is for another issue.

**Comment by zimmski** [comment]
@novoj for the bad folder, create the issue https://github.com/symflower/symflower/issues/26 to track progress on our multi-module support for Java.

**Comment by zimmski** [comment]
@novoj  the first two tests you have posted in the screenshot are due to incomplete code analysis. Could be because we are missing some types. I’d love to hop on a video call with you and sort out the problems to make Symflower work for your projects. The tests should look similar to the last one you posted.  However, I would be also highly interested in your feedback on what tests you would expect so we can make the generation better.
