### ISSUE TITLE
[CLI]Exceeded configured memory limit of 1024MB with 1122MB

### ISSUE THREAD

**Issue by nobutakaes** [symflower/symflower#22]
Hello, I've just installed the plain CLI installer for windows, and on my first test, it returns the following error:

Exceeded configured memory limit of 1024MB with 1122MB and exits.

How can I fix it? Thank you in Advance

**Comment by zimmski** [comment]
Thanks for the report and interest in Symflower!

Since you are using the CLI version: Our default memory limit is 1024MB but you can change the limit with the `--memory-limit` option, e.g. `symflower --memory-limit=2048`. You can also disable the limit using `symflower --memory-limit=0`, but please be aware that Symflower is a memory-hog, it will eat up all your memory if it sees a need. The help `symflower --help` should give you additional options.

We set a default memory limit to not disturb other processes, e.g. to not do too many concurrent calculations. That works usually great for our Java implementation but we do have some problems with the Go implementation of our analysis, so it would be nice to know more about the repository you are looking at. If you can give us access, that would be great to debug Problems.
